# Generated by Django 5.0.5 on 2024-05-12 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("usuario_modifica", models.IntegerField(blank=True, null=True)),
                ("descripcion", models.CharField(max_length=100, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=250, null=True)),
                ("cuil", models.CharField(blank=True, max_length=250, null=True)),
                ("telefono", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
    ]
