# Generated by Django 5.0.5 on 2024-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0002_factura"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="esta_pago",
            new_name="es_compra",
        ),
        migrations.AddField(
            model_name="factura",
            name="es_servicio",
            field=models.BooleanField(default=False),
        ),
    ]
