# Generated by Django 5.0.5 on 2024-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0003_rename_esta_pago_factura_es_compra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="fecha_pago",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
