# Generated by Django 5.0.5 on 2024-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0004_factura_fecha_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="fecha_emision",
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name="factura",
            name="impuestos",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
