# Generated by Django 5.0.5 on 2024-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0005_alter_factura_descuento_alter_factura_fecha_emision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferecia", "Transferencia"),
                    ("debito", "Débito"),
                    ("credito", "Crédito"),
                ],
                default="efectivo",
                max_length=50,
                null=True,
            ),
        ),
    ]
