# Generated by Django 5.0.5 on 2024-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0007_pagoparcial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="descuento",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="impuestos",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="total_con_impuestos",
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado_factura",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de Pago"),
                    ("pagada", "Pagada"),
                    ("vencida", "Vencida"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
