# Generated by Django 5.0.5 on 2024-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0008_remove_factura_descuento_remove_factura_impuestos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="total_pagar",
            field=models.FloatField(),
        ),
    ]
