# Generated by Django 5.0.5 on 2024-05-09 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inv", "0004_unidadmedida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("usuario_modifica", models.IntegerField(blank=True, null=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("codigo_barra", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("precio_compra", models.FloatField(default=0)),
                ("precio_venta", models.FloatField(default=0)),
                ("existencia", models.IntegerField(default=0)),
                ("ultima_compra", models.DateField(blank=True, null=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inv.marca"
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inv.subcategoria",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inv.unidadmedida",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Productos",
                "unique_together": {("codigo", "codigo_barra")},
            },
        ),
    ]
