# Generated by Django 5.0.5 on 2024-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inv", "0005_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="descripcion",
            field=models.CharField(
                help_text="Descripción de la categoría", max_length=100, unique=True
            ),
        ),
    ]
