# Generated by Django 5.0.5 on 2024-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inv", "0007_precio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio_compra",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="precio_venta",
        ),
    ]
