# Generated by Django 5.0.5 on 2024-06-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inv", "0009_producto_precio_venta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inv.marca",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inv.subcategoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inv.unidadmedida",
            ),
        ),
    ]
